import express from "express";
import authRoutes from "./auth.route.js";
import messageRoutes from "./message.route.js";
import friendRoutes from "./friend.route.js";
import conversationRoutes from "./conversation.route.js";
import aiRoutes from "./ai.route.js";
const router = express.Router();
router.use("/auth", authRoutes);
router.use("/messages", messageRoutes);
router.use("/friends", friendRoutes);
router.use("/conversations", conversationRoutes);
router.use("/ai", aiRoutes);
export default router;
